import { Outfit,Ovo } from "next/font/google";
import "./globals.css";
import { html } from "next";

const outfit = Outfit({
  subsets: ["latin"], weight: ["400","500","600","700"]
});

const ovo = Ovo({
  subsets: ["latin"], weight: ["400"]
});

export const metadata = {
  title: "Neel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <html lang="eng" className="scroll-smooth">
    <body 
    className={`${outfit.className} ${ovo.className} antialiased leading-8 over-flow-x-hidden dark:bg-darkTheme dark:text-white`}>
    {children}
    </body>
   </html>
  );
}
  